import type { BlogBlock } from './types'

export const FRIENDLY_BLOCK_LABELS: Partial<Record<BlogBlock['type'], string>> = {
  heading:           'Heading',
  paragraph:         'Text Section',
  rich_text:         'Rich Text',
  intro:             'Introduction',
  quote:             'Customer Quote',
  image_text:        'Photo + Text',
  full_image:        'Full-Width Photo',
  gallery:           'Photo Gallery',
  youtube_video:     'YouTube Video',
  vimeo_video:       'Vimeo Video',
  video:             'Video',
  external_video:    'Video from Another Site',
  button_cta:        'Button / Call to Action',
  cta:               'Call to Action Banner',
  service_callout:   'Service Highlight',
  faq:               'Frequently Asked Questions',
  checklist:         'Checklist',
  service_steps:     'Step-by-Step Process',
  quick_answer:      'Quick Answer Box',
  related_services:  'Related Services',
  related_inventory: 'Related Boats',
  divider:           'Divider Line',
  hero:              'Hero Image',
  before_after:      'Before & After',
  trust_badges:      'Trust Badges',
  specs_table:       'Specs Table',
  comparison_table:  'Comparison Table',
  team_member:       'Team Member Profile',
  warning_signs:     'Warning Signs',
  map:               'Map',
  contact_form:      'Contact Form',
}
