import type { SEOPage, SEOSettings, LocalSEOSettings, RedirectRule, SEOHistoryEntry } from './seoTypes'
import { scoreToHealth } from './seoTypes'

// ─── Shared business profile ──────────────────────────────────────────────────
const TM_LOCAL: LocalSEOSettings = {
  businessName: 'Thomas Marine, LLC',
  primaryCity: 'Georgetown',
  serviceArea: ['Georgetown', 'Pawleys Island', 'Murrells Inlet', 'Myrtle Beach', 'Conway'],
  state: 'South Carolina',
  phone: '(843) 833-8054',
  address: '129 Dozier St, Georgetown, SC 29440',
  hours: 'Mon–Fri 8am–5pm, Sat by appointment',
  googleBusinessUrl: 'https://business.google.com',
  mapUrl: 'https://maps.google.com/?cid=thomas-marine-georgetown',
  brandsServiced: ['Suzuki', 'Mercury', 'Yamaha', 'Honda', 'Evinrude', 'Johnson'],
  brandsSold: ['Suzuki Marine', 'EZ Loader'],
  primaryLocalPhrase: 'Suzuki outboard service in Georgetown, SC',
  secondaryLocalPhrases: ['boat repair Georgetown South Carolina', 'marine service Myrtle Beach'],
  nearbyAreas: ['Pawleys Island', 'Murrells Inlet', 'Myrtle Beach', 'Conway', 'Andrews'],
}

function noHistory(): SEOHistoryEntry[] { return [] }
function noRedirects(): RedirectRule[] { return [] }

// ─── Home Page ────────────────────────────────────────────────────────────────
const homePage: SEOPage = {
  id: 'home',
  name: 'Home',
  pageType: 'core',
  url: '/',
  score: 91,
  health: scoreToHealth(91, false),
  indexStatus: 'index',
  lastUpdated: '2025-04-10',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'home_og_img', severity: 'yellow', category: 'social', title: 'OG image not set explicitly', description: 'Using default fallback hero image for social sharing.', fixType: 'admin_edit', suggestedFix: 'Upload a dedicated 1200×630 social share image.' },
  ],
  settings: {
    seoTitle: 'Thomas Marine, LLC | Boat Sales & Service in Georgetown, SC',
    metaDescription: 'Family-owned marine sales and service in Georgetown, SC. Authorized Suzuki Marine dealer serving Georgetown County and the South Carolina Lowcountry.',
    slug: '',
    canonicalUrl: 'https://thomasmarinellc.com/',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Thomas Marine, LLC | Boat Sales & Service in Georgetown, SC',
    ogDescription: 'Family-owned marine sales and service in Georgetown, SC.',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'marine service Georgetown SC',
    secondaryKeywords: ['Suzuki dealer Georgetown', 'boat repair Georgetown SC', 'repower South Carolina'],
    searchIntent: 'navigational / informational',
    localPhrase: 'marine service Georgetown, South Carolina',
  } as SEOSettings,
  schema: { enabled: true, types: ['Organization', 'LocalBusiness', 'WebSite'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: false },
  images: [
    { id: 'hero_img', src: '/hero.PNG', alt: 'Thomas Marine LLC Georgetown SC marina', caption: '', fileSizeKb: 340, isLazyLoaded: false, isDecorative: false, isOgImage: true, isHeroImage: true, health: 'green', issues: [] },
  ],
  internalLinks: [
    { id: 'il_services', label: 'Our Services', url: '/services', type: 'service', status: 'active' },
    { id: 'il_inventory', label: 'Boat Inventory', url: '/inventory', type: 'inventory', status: 'active' },
    { id: 'il_contact', label: 'Contact Us', url: '/contact', type: 'cta', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 420, hasCTA: true, hasInternalLinks: true, hasFAQ: false, suggestedH2s: ['Our Services', 'Featured Inventory', 'What Our Customers Say'] },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Services Index ───────────────────────────────────────────────────────────
const servicesPage: SEOPage = {
  id: 'services',
  name: 'Services',
  pageType: 'category',
  url: '/services',
  score: 84,
  health: scoreToHealth(84, false),
  indexStatus: 'index',
  lastUpdated: '2025-03-15',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'srv_schema', severity: 'yellow', category: 'schema', title: 'No Service schema', description: 'Category page lists services but has no structured data.', fixType: 'auto_fix', suggestedFix: 'Enable Service schema for top-level service categories.' },
    { id: 'srv_local', severity: 'yellow', category: 'local', title: 'Local phrase missing from meta description', description: 'Meta description does not include a city/state phrase.', fixType: 'admin_edit' },
  ],
  settings: {
    seoTitle: 'Marine Services | Thomas Marine, LLC',
    metaDescription: 'Expert marine service from factory-trained technicians. Oil changes, repowers, winterization, detailing and more.',
    slug: 'services',
    canonicalUrl: 'https://thomasmarinellc.com/services',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Marine Services | Thomas Marine, LLC',
    ogDescription: 'Expert marine service from factory-trained technicians.',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'marine services Georgetown SC',
    secondaryKeywords: ['boat service Georgetown', 'outboard service South Carolina'],
    searchIntent: 'commercial',
    localPhrase: 'marine services Georgetown, SC',
  } as SEOSettings,
  schema: { enabled: false, types: ['Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: true },
  images: [],
  internalLinks: [
    { id: 'il_oil', label: 'Oil Changes', url: '/services/oil-changes', type: 'service', status: 'active' },
    { id: 'il_repower', label: 'Repower', url: '/services/repower', type: 'service', status: 'active' },
    { id: 'il_winter', label: 'Winterization', url: '/services/winterization', type: 'service', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 280, hasCTA: true, hasInternalLinks: true, hasFAQ: false },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Suzuki Outboards (Service Page) ─────────────────────────────────────────
const suzukiPage: SEOPage = {
  id: 'suzuki-outboards',
  name: 'Suzuki Outboards',
  pageType: 'service',
  url: '/services/suzuki-outboards',
  score: 78,
  health: scoreToHealth(78, false),
  indexStatus: 'index',
  lastUpdated: '2025-02-20',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'sz_faq', severity: 'yellow', category: 'content', title: 'No FAQ content', description: 'Service pages with FAQ schema rank better for question queries.', fixType: 'admin_edit', suggestedFix: 'Add 3–5 FAQs about Suzuki outboard service.' },
    { id: 'sz_word', severity: 'yellow', category: 'content', title: 'Low word count (310)', description: 'Thin content may underperform for competitive service terms.', fixType: 'admin_edit' },
    { id: 'sz_schema', severity: 'yellow', category: 'schema', title: 'FAQ schema not enabled', description: 'Page lacks FAQ schema despite being ideal for it.', fixType: 'auto_fix' },
  ],
  settings: {
    seoTitle: 'Suzuki Outboard Service in Georgetown, SC | Thomas Marine, LLC',
    metaDescription: 'Factory-trained Suzuki outboard service in Georgetown, SC. Oil changes, diagnostics, repairs and repowers from an authorized Suzuki Marine dealer.',
    slug: 'suzuki-outboards',
    canonicalUrl: 'https://thomasmarinellc.com/services/suzuki-outboards',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Suzuki Outboard Service | Thomas Marine',
    ogDescription: 'Authorized Suzuki Marine dealer. Factory-trained service in Georgetown, SC.',
    ogImageUrl: '/images/blogs/ThomasMarineEngineInstallationServiceFlyer.png',
    socialImageUrl: '/images/blogs/ThomasMarineEngineInstallationServiceFlyer.png',
    primaryKeyword: 'Suzuki outboard service Georgetown SC',
    secondaryKeywords: ['Suzuki Marine dealer Georgetown', 'outboard repair South Carolina'],
    searchIntent: 'commercial',
    localPhrase: 'Suzuki outboard service Georgetown, South Carolina',
  } as SEOSettings,
  schema: { enabled: true, types: ['Service', 'LocalBusiness', 'Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: true },
  images: [
    { id: 'sz_img1', src: '/images/blogs/ThomasMarineEngineInstallationServiceFlyer.png', alt: 'Suzuki engine installation service', caption: '', fileSizeKb: 280, isLazyLoaded: true, isDecorative: false, isOgImage: true, isHeroImage: true, health: 'green', issues: [] },
  ],
  internalLinks: [
    { id: 'il_schedule', label: 'Schedule Service', url: '/contact', type: 'cta', status: 'active' },
    { id: 'il_oil', label: 'Outboard Oil Changes', url: '/services/oil-changes', type: 'service', status: 'active' },
    { id: 'il_repower', label: 'Suzuki Repower', url: '/services/repower', type: 'service', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 310, hasCTA: true, hasInternalLinks: true, hasFAQ: false, suggestedFAQs: ['How often should I service my Suzuki outboard?', 'Do you offer Suzuki warranty service?', 'What Suzuki models do you service?'] },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── De-Winterization (Service — Yellow) ─────────────────────────────────────
const deWinterPage: SEOPage = {
  id: 'de-winterization',
  name: 'De-Winterization',
  pageType: 'service',
  url: '/services/de-winterization',
  score: 72,
  health: scoreToHealth(72, false),
  indexStatus: 'index',
  lastUpdated: '2025-01-05',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'dw_meta', severity: 'yellow', category: 'metadata', title: 'Meta description too short (87 chars)', description: 'Ideal length is 150–160 characters for maximum SERP visibility.', fixType: 'admin_edit' },
    { id: 'dw_img_alt', severity: 'yellow', category: 'images', title: 'Hero image missing descriptive alt text', description: 'Alt text is present but generic.', fixType: 'admin_edit' },
    { id: 'dw_internal', severity: 'yellow', category: 'links', title: 'Only 1 internal link', description: 'Service pages should link to at least 3 related pages.', fixType: 'admin_edit' },
  ],
  settings: {
    seoTitle: 'De-Winterization Service | Thomas Marine, LLC',
    metaDescription: 'Spring boat commissioning and de-winterization in Georgetown, SC.',
    slug: 'de-winterization',
    canonicalUrl: 'https://thomasmarinellc.com/services/de-winterization',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'De-Winterization | Thomas Marine',
    ogDescription: 'Get your boat ready for spring. De-winterization service from Thomas Marine.',
    ogImageUrl: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png',
    socialImageUrl: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png',
    primaryKeyword: 'boat de-winterization Georgetown SC',
    secondaryKeywords: ['spring boat commissioning South Carolina'],
    searchIntent: 'commercial',
    localPhrase: 'boat de-winterization Georgetown, SC',
  } as SEOSettings,
  schema: { enabled: true, types: ['Service', 'Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: true },
  images: [
    { id: 'dw_img1', src: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png', alt: 'Spring commissioning', caption: '', fileSizeKb: 260, isLazyLoaded: true, isDecorative: false, isOgImage: true, isHeroImage: true, health: 'yellow', issues: ['Alt text is generic — add location and service name'] },
  ],
  internalLinks: [
    { id: 'il_contact2', label: 'Schedule De-Winterization', url: '/contact', type: 'cta', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 270, hasCTA: true, hasInternalLinks: true, hasFAQ: false },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Inventory (Red — missing metadata) ──────────────────────────────────────
const inventoryPage: SEOPage = {
  id: 'inventory',
  name: 'Inventory',
  pageType: 'inventory',
  url: '/inventory',
  score: 61,
  health: scoreToHealth(61, true),
  indexStatus: 'index',
  lastUpdated: '2025-05-01',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'inv_meta', severity: 'red', category: 'metadata', title: 'Missing meta description', description: 'This page has no meta description. Google will auto-generate one, often poorly.', fixType: 'auto_fix', suggestedFix: 'Browse pre-owned boats for sale in Georgetown, SC. Thomas Marine offers quality used boats, outboards, and trailers.' },
    { id: 'inv_schema', severity: 'red', category: 'schema', title: 'No Product or Offer schema', description: 'Inventory listings should use structured data for rich results.', fixType: 'auto_fix' },
    { id: 'inv_h1', severity: 'yellow', category: 'content', title: 'H1 does not include location', description: 'Adding a city improves local relevance.', fixType: 'admin_edit' },
  ],
  settings: {
    seoTitle: 'Pre-Owned Boats for Sale in Georgetown, SC | Thomas Marine',
    metaDescription: '',
    slug: 'inventory',
    canonicalUrl: 'https://thomasmarinellc.com/inventory',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Pre-Owned Boat Inventory | Thomas Marine',
    ogDescription: '',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'used boats for sale Georgetown SC',
    secondaryKeywords: ['pre-owned boats South Carolina', 'boat dealership Georgetown'],
    searchIntent: 'transactional',
    localPhrase: 'used boats for sale Georgetown, South Carolina',
  } as SEOSettings,
  schema: { enabled: false, types: ['Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: true, useServiceData: false },
  images: [],
  internalLinks: [
    { id: 'il_contact3', label: 'Ask About Financing', url: '/contact', type: 'cta', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: true, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: true, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: false, wordCount: 90, hasCTA: true, hasInternalLinks: true, hasFAQ: false, suggestedH1: 'Pre-Owned Boats for Sale in Georgetown, SC' },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Blog Landing ─────────────────────────────────────────────────────────────
const blogLandingPage: SEOPage = {
  id: 'blog',
  name: 'Knowledge Hub (Blog)',
  pageType: 'category',
  url: '/blog',
  score: 80,
  health: scoreToHealth(80, false),
  indexStatus: 'index',
  lastUpdated: '2025-04-01',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'blog_schema', severity: 'yellow', category: 'schema', title: 'No Article index schema', description: 'Blog landing page should use CollectionPage or BlogPosting list schema.', fixType: 'auto_fix' },
  ],
  settings: {
    seoTitle: 'Marine Knowledge Hub | Thomas Marine, LLC',
    metaDescription: 'Boat maintenance tips, buying guides, and marine service advice from Thomas Marine LLC — your Georgetown, SC Suzuki Marine dealer.',
    slug: 'blog',
    canonicalUrl: 'https://thomasmarinellc.com/blog',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Marine Knowledge Hub | Thomas Marine',
    ogDescription: 'Expert tips and guides from Thomas Marine.',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'boat maintenance tips Georgetown SC',
    secondaryKeywords: ['marine advice South Carolina', 'outboard maintenance guide'],
    searchIntent: 'informational',
    localPhrase: 'boat tips Georgetown South Carolina',
  } as SEOSettings,
  schema: { enabled: false, types: ['Breadcrumb'], useBusinessProfile: false, usePageFAQ: false, useInventoryData: false, useServiceData: false },
  images: [],
  internalLinks: [],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 180, hasCTA: false, hasInternalLinks: true, hasFAQ: false },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Contact Page ─────────────────────────────────────────────────────────────
const contactPage: SEOPage = {
  id: 'contact',
  name: 'Contact',
  pageType: 'core',
  url: '/contact',
  score: 88,
  health: scoreToHealth(88, false),
  indexStatus: 'index',
  lastUpdated: '2025-02-10',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'cnt_map', severity: 'yellow', category: 'schema', title: 'No Map schema', description: 'Contact page should include LocalBusiness + ContactPoint schema.', fixType: 'auto_fix' },
  ],
  settings: {
    seoTitle: 'Contact Thomas Marine, LLC | Georgetown, SC',
    metaDescription: 'Contact Thomas Marine, LLC in Georgetown, SC. Call (843) 833-8054, visit us at 129 Dozier St, or submit a service inquiry online.',
    slug: 'contact',
    canonicalUrl: 'https://thomasmarinellc.com/contact',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Contact Thomas Marine | Georgetown, SC',
    ogDescription: 'Reach our service team at (843) 833-8054 or visit us in Georgetown.',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'contact Thomas Marine Georgetown SC',
    secondaryKeywords: ['boat service Georgetown phone', 'marine shop Georgetown SC'],
    searchIntent: 'navigational',
    localPhrase: 'marine service contact Georgetown, SC',
  } as SEOSettings,
  schema: { enabled: true, types: ['LocalBusiness', 'ContactPoint'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: false },
  images: [],
  internalLinks: [
    { id: 'il_services2', label: 'Browse Services', url: '/services', type: 'service', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: false, wordCount: 200, hasCTA: true, hasInternalLinks: true, hasFAQ: false },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Used Boat Buying Guide (Blog Post) ───────────────────────────────────────
const buyingGuidePage: SEOPage = {
  id: 'used-boat-buying-guide',
  name: 'Used Boat Buying Guide',
  pageType: 'blog',
  url: '/blog/used-boat-buying-guide',
  score: 93,
  health: scoreToHealth(93, false),
  indexStatus: 'index',
  lastUpdated: '2025-03-22',
  lastSEOScan: '2025-05-20',
  issues: [],
  settings: {
    seoTitle: 'Used Boat Buying Guide | Thomas Marine Knowledge Hub',
    metaDescription: 'Everything you need to know before buying a used boat in South Carolina. Thomas Marine\'s complete guide to pre-owned boat buying.',
    slug: 'used-boat-buying-guide',
    canonicalUrl: 'https://thomasmarinellc.com/blog/used-boat-buying-guide',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Used Boat Buying Guide | Thomas Marine',
    ogDescription: 'Everything you need to know before buying a used boat.',
    ogImageUrl: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png',
    socialImageUrl: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png',
    primaryKeyword: 'used boat buying guide South Carolina',
    secondaryKeywords: ['pre-owned boat tips', 'boat inspection checklist'],
    searchIntent: 'informational',
    localPhrase: 'buying a used boat Georgetown SC',
  } as SEOSettings,
  schema: { enabled: true, types: ['Article', 'FAQ', 'Breadcrumb'], useBusinessProfile: false, usePageFAQ: true, useInventoryData: false, useServiceData: false },
  images: [
    { id: 'bg_img1', src: '/images/blogs/ThomasMarineSpringCommissioningFlyer.png', alt: 'Spring boat commissioning checklist', caption: 'Thomas Marine spring checklist', fileSizeKb: 260, isLazyLoaded: true, isDecorative: false, isOgImage: true, isHeroImage: true, health: 'green', issues: [] },
  ],
  internalLinks: [
    { id: 'il_inv2', label: 'View Pre-Owned Inventory', url: '/inventory', type: 'inventory', status: 'active' },
    { id: 'il_contact4', label: 'Schedule Boat Inspection', url: '/contact', type: 'cta', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 1240, hasCTA: true, hasInternalLinks: true, hasFAQ: true },
  redirects: noRedirects(),
  history: [
    { id: 'hist_1', pageId: 'used-boat-buying-guide', changedBy: 'admin', field: 'metaDescription', oldValue: 'A guide to buying used boats.', newValue: 'Everything you need to know before buying a used boat in South Carolina...', changedAt: '2025-03-22T14:00:00Z', reason: 'Expanded meta to full length' },
  ],
}

// ─── Featured Inventory Listing (Red — structural issues) ─────────────────────
const featuredInventoryPage: SEOPage = {
  id: 'featured-inventory-listing',
  name: 'Featured Inventory Listing',
  pageType: 'inventory',
  url: '/inventory/2023-suzuki-df150',
  score: 55,
  health: scoreToHealth(55, true),
  indexStatus: 'index',
  lastUpdated: '2025-05-10',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'fil_img', severity: 'red', category: 'images', title: 'No product image', description: 'Inventory listings with no image score poorly and convert at lower rates.', fixType: 'admin_edit' },
    { id: 'fil_avail', severity: 'red', category: 'technical', title: 'No availability status', description: 'Product schema requires availability. Missing this blocks rich results.', fixType: 'admin_edit' },
    { id: 'fil_desc', severity: 'yellow', category: 'metadata', title: 'Meta description is auto-generated', description: 'Auto-generated descriptions often miss key selling points.', fixType: 'admin_edit' },
  ],
  settings: {
    seoTitle: '2023 Suzuki DF150 for Sale in Georgetown, SC | Thomas Marine',
    metaDescription: '',
    slug: '2023-suzuki-df150',
    canonicalUrl: 'https://thomasmarinellc.com/inventory/2023-suzuki-df150',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: '2023 Suzuki DF150 | Thomas Marine Georgetown SC',
    ogDescription: '',
    ogImageUrl: '',
    socialImageUrl: '',
    primaryKeyword: '2023 Suzuki DF150 for sale Georgetown SC',
    secondaryKeywords: ['Suzuki outboard for sale South Carolina'],
    searchIntent: 'transactional',
    localPhrase: 'outboard motors for sale Georgetown, SC',
  } as SEOSettings,
  schema: { enabled: false, types: ['Product', 'Offer', 'Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: true, useServiceData: false },
  images: [],
  internalLinks: [
    { id: 'il_contact5', label: 'Ask About This Motor', url: '/contact', type: 'cta', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: true, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: true, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: false, wordCount: 120, hasCTA: true, hasInternalLinks: true, hasFAQ: false },
  redirects: noRedirects(),
  history: noHistory(),
}

// ─── Outboard Diagnostics ─────────────────────────────────────────────────────
const diagnosticsPage: SEOPage = {
  id: 'outboard-diagnostics',
  name: 'Outboard Diagnostics',
  pageType: 'service',
  url: '/services/outboard-diagnostics',
  score: 66,
  health: scoreToHealth(66, true),
  indexStatus: 'index',
  lastUpdated: '2024-11-01',
  lastSEOScan: '2025-05-20',
  issues: [
    { id: 'diag_title', severity: 'red', category: 'metadata', title: 'SEO title missing city', description: 'Service page title should include location for local ranking.', fixType: 'admin_edit', suggestedFix: 'Outboard Diagnostics in Georgetown, SC | Thomas Marine, LLC' },
    { id: 'diag_cta', severity: 'red', category: 'content', title: 'No clear CTA', description: 'Service pages must have a call-to-action linking to the contact/schedule page.', fixType: 'admin_edit' },
    { id: 'diag_age', severity: 'yellow', category: 'content', title: 'Content not updated in 6+ months', description: 'Stale service pages may lose freshness signals.', fixType: 'admin_edit' },
  ],
  settings: {
    seoTitle: 'Outboard Engine Diagnostics | Thomas Marine',
    metaDescription: 'Professional outboard diagnostics for Suzuki, Yamaha, Mercury, and more. Find and fix engine issues fast.',
    slug: 'outboard-diagnostics',
    canonicalUrl: 'https://thomasmarinellc.com/services/outboard-diagnostics',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Outboard Diagnostics | Thomas Marine',
    ogDescription: 'Professional outboard engine diagnostics from Thomas Marine.',
    ogImageUrl: '/hero.PNG',
    socialImageUrl: '/hero.PNG',
    primaryKeyword: 'outboard diagnostics Georgetown SC',
    secondaryKeywords: ['outboard engine check South Carolina'],
    searchIntent: 'commercial',
    localPhrase: 'outboard diagnostics Georgetown, South Carolina',
  } as SEOSettings,
  schema: { enabled: true, types: ['Service', 'Breadcrumb'], useBusinessProfile: true, usePageFAQ: false, useInventoryData: false, useServiceData: true },
  images: [],
  internalLinks: [],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 250, hasCTA: false, hasInternalLinks: false, hasFAQ: false, suggestedCTA: 'Schedule a Diagnostic Appointment' },
  redirects: [
    { id: 'rd_1', fromUrl: '/services/diagnostics', toUrl: '/services/outboard-diagnostics', type: '301', createdAt: '2024-11-01', createdBy: 'admin', hitCount: 42, status: 'active', notes: 'Slug cleanup redirect' },
  ],
  history: noHistory(),
}

// ─── Repower Service ──────────────────────────────────────────────────────────
const repowerPage: SEOPage = {
  id: 'repower',
  name: 'Repower',
  pageType: 'service',
  url: '/services/repower',
  score: 95,
  health: scoreToHealth(95, false),
  indexStatus: 'index',
  lastUpdated: '2025-04-18',
  lastSEOScan: '2025-05-20',
  issues: [],
  settings: {
    seoTitle: 'Boat Repower with Suzuki Outboards in Georgetown, SC | Thomas Marine',
    metaDescription: 'Upgrade your boat with a new Suzuki outboard. Thomas Marine handles full repowers — from sizing consultation to installation and sea trial in Georgetown, SC.',
    slug: 'repower',
    canonicalUrl: 'https://thomasmarinellc.com/services/repower',
    useDefaultCanonical: true,
    indexSetting: 'index',
    followSetting: 'follow',
    robotsSnippet: true,
    includeInSitemap: true,
    ogTitle: 'Suzuki Repower Service | Thomas Marine Georgetown SC',
    ogDescription: 'Replace your old outboard with a new Suzuki. Expert repower service from Thomas Marine.',
    ogImageUrl: '/images/blogs/ThomasMarineRepowerFlyer.png',
    socialImageUrl: '/images/blogs/ThomasMarineRepowerFlyer.png',
    primaryKeyword: 'Suzuki repower Georgetown SC',
    secondaryKeywords: ['outboard repower South Carolina', 'new Suzuki outboard installation'],
    searchIntent: 'commercial',
    localPhrase: 'boat repower Georgetown, South Carolina',
  } as SEOSettings,
  schema: { enabled: true, types: ['Service', 'LocalBusiness', 'FAQ', 'Breadcrumb'], useBusinessProfile: true, usePageFAQ: true, useInventoryData: false, useServiceData: true },
  images: [
    { id: 'rp_img1', src: '/images/blogs/ThomasMarineRepowerFlyer.png', alt: 'Suzuki outboard repower service Georgetown SC', caption: '', fileSizeKb: 290, isLazyLoaded: true, isDecorative: false, isOgImage: true, isHeroImage: true, health: 'green', issues: [] },
  ],
  internalLinks: [
    { id: 'il_schedule3', label: 'Get a Repower Quote', url: '/contact', type: 'cta', status: 'active' },
    { id: 'il_suzuki2', label: 'Suzuki Outboards', url: '/services/suzuki-outboards', type: 'service', status: 'active' },
    { id: 'il_inv3', label: 'View Suzuki Inventory', url: '/inventory', type: 'inventory', status: 'active' },
  ],
  localSEO: TM_LOCAL,
  technical: { httpStatus: 200, isIndexable: true, robotsBlocked: false, canonicalIsCorrect: true, inSitemap: true, hasDuplicateTitle: false, hasDuplicateMeta: false, hasDuplicateSlug: false, brokenInternalLinks: [], missingRedirects: [], hasStructuredDataErrors: false, mobileWarning: false, imageSizeWarning: false },
  content: { hasH1: true, h1Count: 1, hasH2s: true, wordCount: 680, hasCTA: true, hasInternalLinks: true, hasFAQ: true },
  redirects: noRedirects(),
  history: noHistory(),
}

export const MOCK_SEO_PAGES: SEOPage[] = [
  homePage,
  servicesPage,
  suzukiPage,
  deWinterPage,
  inventoryPage,
  blogLandingPage,
  contactPage,
  buyingGuidePage,
  featuredInventoryPage,
  diagnosticsPage,
  repowerPage,
]
